name: Flutter Checks

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.3.10'
      - name: Flutter Formatting Check
        run: flutter format --set-exit-if-changed $(git diff --name-only origin/main HEAD | grep '.dart')
      - name: Flutter Analyze
        run: flutter analyze $(git diff --name-only origin/main HEAD | grep '.dart')

